export const ACTION_TYPE = {
    SET_USER_NAME: 'SET_USER_NAME',
    SET_USER_REPOS: 'SET_USER_REPOS',
    SET_USER_REPOS_FETCHING: 'SET_USER_REPOS_FETCHING',
    SET_USER_REPOS_FETCHED: 'SET_USER_REPOS_FETCHED',
    SET_USER_ORGS: 'SET_USER_ORGS',
    SET_USER_ORGS_FETCHING: 'SET_USER_ORGS_FETCHING',
    SET_USER_ORGS_FETCHED: 'SET_USER_ORGS_FETCHED',
    // ERRORS
    SET_USER_NAME_ERROR: 'SET_USER_NAME_ERROR',
    SET_USER_REPOS_ERROR: 'SET_USER_REPOS_ERROR',
    SET_USER_ORGS_ERROR: 'SET_USER_ORGS_ERROR',
    // CLEAR DATA
    CLEAR_CURRENT_USER_DATA: 'CLEAR_CURRENT_USER_DATA'
}